### ISSUE TITLE
ридми вообще непонятный

### ISSUE THREAD

**Issue by ghost** [Woooj/javawebproject#1]
В ридми написано что надо запустить schema.sql - как запустить? где запустить? какие команды выполнить?

Вы должны ридми писать так понятно, чтобы ваша Бабушка его смогла понять и сделать. А то что щас в ридми - это какая-то отписка.

**Comment by Woooj** [comment]
Да, понял.
Перепишу.

**Comment by ghost** [comment]
Желательно чтобы система все эти вещи делала сама автоматически - я должен только скачать программу, запустить 1 (одну), ну максимум две команды (всё должно запуститься как надо и само настроиться) и получить готовый результат, пройдя в браузере по адресу, который мне должен где-то показаться

**Comment by ghost** [comment]
Кстати респект за быстрый фидбэк

**Comment by Woooj** [comment]
И последний вопрос: мне в ответе сказали, что «на сервер по аджаксу не
ходим», а как тогда? Я думал клиент посредством аджакса кидает гет-запрос,
а сервер отвечает?

**Comment by ghost** [comment]
Наоборот - на сервер надо ходить по аджаксу.

На сервер нужно ходить ИМЕННО по АДЖАКСУ

**Comment by Woooj** [comment]
"ERROR: На сервер НЕ ходим по аджаксу - а это важно." Вот этот момент не
понял

**Comment by ghost** [comment]
Имеется в виду что сейчас не ходим, а ходить нужно, и это важно. Замешательство получилось из-за пропущенной фразу: "а ходить нужно"
